import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './supabase';
import { deal26 } from './game';
import './styles.css';
const id=()=>crypto.randomUUID();const room=()=>new URLSearchParams(location.search).get('room')?.toUpperCase()||'';
function App(){const[pid]=useState(()=>sessionStorage.getItem('baazi-pid')||id()),[name,setName]=useState(''),[code,setCode]=useState(room()),[s,setS]=useState<any|null>(null),[cut,setCut]=useState(26),[msg,setMsg]=useState('');useEffect(()=>sessionStorage.setItem('baazi-pid',pid),[pid]);
async function create(){let c=Math.random().toString(36).slice(2,8).toUpperCase();let st:any={phase:'waiting',players:[],hands:{},floor:[],secondHalf:[],deck:[],hostPlayerId:pid,turnPlayerId:null,calledValue:null};let{error}=await supabase.from('baazi_rooms').insert({code:c,state:st});if(error)return setMsg(error.message);setCode(c);history.replaceState({},'',`?room=${c}`);setMsg('Share this link with Sydney.')}
async function join(){let{data,error}=await supabase.from('baazi_rooms').select('*').eq('code',code.toUpperCase()).single();if(error||!data)return setMsg('Table not found.');let st=data.state as any;if(!st.players.some(p=>p.id===pid)){if(st.players.length>=4)return setMsg('Table full.');st={...st,players:[...st.players,{id:pid,name:name.trim()||'Player'}]};let u=await supabase.from('baazi_rooms').update({state:st}).eq('code',code.toUpperCase());if(u.error)return setMsg(u.error.message)}setS(st);history.replaceState({},'',`?room=${code.toUpperCase()}`)}
useEffect(()=>{if(!code)return;join();let ch=supabase.channel('room-'+code).on('postgres_changes',{event:'*',schema:'public',table:'baazi_rooms',filter:`code=eq.${code}`},p=>p.new&&setS((p.new as any).state)).subscribe();return()=>{supabase.removeChannel(ch)}},[code]);
async function deal(){if(!s||s.players.length!==2)return setMsg('Exactly two players for this test.');let x=deal26(s.players,cut);let n={...s,phase:'dealing' as const,...x,turnPlayerId:s.players[1].id};await supabase.from('baazi_rooms').update({state:n}).eq('code',code);setS(n)}
let me=s?.hands[pid]||[];let show=(c)=>c.rank+c.suit;return <main><header><b>BAAZI</b><small>Aajo baazi la layiye.</small></header>{!s?<section><h1>Family table.</h1><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><div><input placeholder="Room code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button onClick={join}>Join</button></div><button onClick={create}>Create table</button><p>{msg}</p></section>:<><section className="table"><div className="players">{s.players.map(p=><span key={p.id}>{p.name}</span>)}</div><h3>FLOOR</h3><div className="cards">{s.floor.map(c=><i key={c.id}>{show(c)}</i>)}</div><h3>{s.players.find(p=>p.id===pid)?.name} · {me.length} cards</h3><div className="cards">{me.map(c=><i key={c.id}>{show(c)}</i>)}</div></section><section><p>Room: {code}</p>{s.phase==='waiting'&&s.hostPlayerId===pid&&s.players.length===2&&<><label>Harry's cut: {cut}</label><input type="range" min="1" max="51" value={cut} onChange={e=>setCut(+e.target.value)}/><button onClick={deal}>Deal opening 26</button></>}</section></>}</main>}createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);